- ros_topic_name: /clock
  gz_topic_name: /clock
  ros_type_name: rosgraph_msgs/msg/Clock
  gz_type_name: gz.msgs.Clock
  direction: GZ_TO_ROS
- ros_topic_name: /demo_object/attach
  gz_topic_name: /demo_object/attach
  ros_type_name: std_msgs/msg/Empty
  gz_type_name: gz.msgs.Empty
  direction: ROS_TO_GZ
- ros_topic_name: /demo_object/detach
  gz_topic_name: /demo_object/detach
  ros_type_name: std_msgs/msg/Empty
  gz_type_name: gz.msgs.Empty
  direction: ROS_TO_GZ
- ros_topic_name: /demo_object/attached
  gz_topic_name: /demo_object/attached
  ros_type_name: std_msgs/msg/String
  gz_type_name: gz.msgs.StringMsg
  direction: GZ_TO_ROS
- ros_topic_name: /gazebo/model_poses
  gz_topic_name: /world/lift_pick_place/pose/info
  ros_type_name: tf2_msgs/msg/TFMessage
  gz_type_name: gz.msgs.Pose_V
  direction: GZ_TO_ROS
